kind: pipeline
name: serverless-template

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.hub.docker.com/unfor19/serverless-template
      registry: registry.hub.docker.com
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      auto_tag: true
      dockerfile: Dockerfile
